name: deploy
on:
  push:
    branches: [ main ]
  workflow_dispatch:
permissions:
  contents: read
  id-token: write
env:
  ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  ARM_USE_OIDC: "true"
  ARM_ENVIRONMENT: "usgovernment"
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
      - name: Terraform init + apply
        working-directory: infra
        run: |
          terraform init -input=false
          terraform apply -input=false -auto-approve
